hetznercloud/apps

.github/cleanup.sh
=> cleanup ssh-keys

apps/hetzner/lamp/files/opt/hcloud/lamp_setup.sh, apps/hetzner/nextcloud/files/opt/hcloud/nextcloud_setup.sh, apps/hetzner/wordpress/files/opt/hcloud/wp_setup.sh
=> reload apache2 after certbot run

.github/workflows/packer-big-blue-button.yml, .github/workflows/packer-docker-ce.yml, .github/workflows/packer-gitlab.yml, .github/workflows/packer-jitsi.yml, .github/workflows/packer-lamp.yml, .github/workflows/packer-nextcloud.yml, .github/workflows/packer-wordpress.yml
=> listen for workflow_dispatch events

apps/hetzner/gitlab/metadata.json, apps/hetzner/gitlab/template.pkr.hcl
=> [GitLab] Update to 14.2

apps/hetzner/nextcloud/metadata.json, apps/hetzner/nextcloud/template.pkr.hcl
=> [Nextcloud] Update to 22.1.1

apps/hetzner/wordpress/metadata.json, apps/hetzner/wordpress/scripts/wp-install.sh, apps/hetzner/wordpress/template.pkr.hcl
=> [Wordpress] Update to 5.8.1

apps/hetzner/gitlab/metadata.json, apps/hetzner/gitlab/template.pkr.hcl
=> [GitLab] Update to 14.3

.github/actions/build-image/action.yml, .github/workflows/packer-big-blue-button.yml, .github/workflows/packer-docker-ce.yml, .github/workflows/packer-gitlab.yml, .github/workflows/packer-jitsi.yml, .github/workflows/packer-lamp.yml, .github/workflows/packer-nextcloud.yml, .github/workflows/packer-wordpress.yml
The image builds run at UTC midnight. My plan is to trigger the internal snapshot -> app process during core hours (10am or so)
=> Daily image build triggers

apps/hetzner/big-blue-button/scripts/bbb-install.sh, apps/hetzner/big-blue-button/template.pkr.hcl, apps/hetzner/jitsi/files/opt/hcloud/jitsi_setup.sh, apps/hetzner/jitsi/scripts/jitsi-pre-install.sh, apps/hetzner/jitsi/template.pkr.hcl
- Update BBB to 2.4.4
- Remove unnecessary package pins
- Update Jitsi to 2.0.6865-2
=> Update Jitsi and BBB

apps/hetzner/jitsi/metadata.json, apps/hetzner/jitsi/template.pkr.hcl
Change Jitsi Version to 2 and install `2*` as installing a specific version leads to broken package dependencies. (probably bug in the package)
=> Change Jitsi App Version to 2

apps/hetzner/gitlab/metadata.json, apps/hetzner/gitlab/template.pkr.hcl
=> [GitLab] Update to 14.9

apps/hetzner/gitlab/metadata.json, apps/hetzner/gitlab/template.pkr.hcl
=> [GitLab] Update to 14.10

apps/hetzner/wordpress/metadata.json, apps/hetzner/wordpress/template.pkr.hcl
=> [Wordpress] Update to 6.0

apps/hetzner/nextcloud/metadata.json, apps/hetzner/nextcloud/template.pkr.hcl
=> [Nextcloud] Update to 24.0.1

apps/hetzner/gitlab/metadata.json, apps/hetzner/gitlab/template.pkr.hcl
=> [GitLab] Update to 15.0

apps/hetzner/wireguard/README.de.md, apps/hetzner/wireguard/README.md
Add a new video to the README file of WireGuard that shows how to create a server with the WireGuard app, how to configure the domain and admin password via a CLI, and how to configure the first client.
=> Add video to the README file of WireGuard

apps/hetzner/gitlab/metadata.json, apps/hetzner/gitlab/template.pkr.hcl, apps/hetzner/gitlab/test.sh
=> [GitLab] Update to 15.6 and Ubuntu to 22.04

apps/hetzner/go/metadata.json, apps/hetzner/go/template.pkr.hcl
=> [Go] Update to 1.19.4

apps/hetzner/nextcloud/metadata.json, apps/hetzner/nextcloud/scripts/nextcloud-install.sh, apps/hetzner/nextcloud/template.pkr.hcl
=> [Nextcloud] Update to 25.0.2 and Ubuntu to 22.04

apps/hetzner/wordpress/metadata.json, apps/hetzner/wordpress/scripts/wp-install.sh, apps/hetzner/wordpress/template.pkr.hcl
=> [Wordpress] Update to 6.1.1 and Ubuntu to 22.04

apps/hetzner/lamp/metadata.json, apps/hetzner/lamp/template.pkr.hcl
=> [LAMP] Update Ubuntu to 22.04

apps/hetzner/go/metadata.json, apps/hetzner/go/template.pkr.hcl
This is a test because the CI seems to be stuck in #80
=> [Go] Update to 1.20.1

apps/hetzner/collab-tools/README.de.md, apps/hetzner/collab-tools/README.md
There is a small confusing typo in the database name.
=> Fix typo in PostgreSQL for clarity
